enum SceneCardStatus {
  draft, // 仅文字
  generating, // 正在生成图片
  completed, // 图片已生成并下载
  failed, // 生成失败
}

class SceneCard {
  final String id;
  int? startParagraphIndex;
  int? endParagraphIndex;
  final String title;
  final String location;
  final String time;
  final String characters;
  String action;
  final String mood;
  final String visualAnchors;
  final String lighting;
  final String composition;
  final String palette;

  // 生成状态相关
  SceneCardStatus status;
  String? jobId;
  String? localImagePath; // 本地图片路径
  String? errorMsg;
  DateTime? createdAt;

  SceneCard({
    required this.id,
    this.startParagraphIndex,
    this.endParagraphIndex,
    required this.title,
    required this.location,
    required this.time,
    required this.characters,
    required this.action,
    required this.mood,
    required this.visualAnchors,
    required this.lighting,
    required this.composition,
    required this.palette,
    this.status = SceneCardStatus.draft,
    this.jobId,
    this.localImagePath,
    this.errorMsg,
    this.createdAt,
  });

  // 用于序列化存储
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'startParagraphIndex': startParagraphIndex,
      'endParagraphIndex': endParagraphIndex,
      'title': title,
      'location': location,
      'time': time,
      'characters': characters,
      'action': action,
      'mood': mood,
      'visual_anchors': visualAnchors,
      'lighting': lighting,
      'composition': composition,
      'palette': palette,
      'status': status.index,
      'jobId': jobId,
      'localImagePath': localImagePath,
      'errorMsg': errorMsg,
      'createdAt': createdAt?.millisecondsSinceEpoch,
    };
  }

  factory SceneCard.fromJson(Map<String, dynamic> json) {
    final int? start = json['startParagraphIndex'];
    final int? end = json['endParagraphIndex'];
    return SceneCard(
      id: json['id'] ?? '',
      startParagraphIndex: start,
      endParagraphIndex: end,
      title: json['title'] ?? '',
      location: json['location'] ?? '',
      time: json['time'] ?? '',
      characters: json['characters'] ?? '',
      action: json['action'] ?? '',
      mood: json['mood'] ?? '',
      visualAnchors: json['visual_anchors'] ?? '',
      lighting: json['lighting'] ?? '',
      composition: json['composition'] ?? '',
      palette: json['palette'] ?? '',
      status: SceneCardStatus.values[json['status'] ?? 0],
      jobId: json['jobId'],
      localImagePath: json['localImagePath'],
      errorMsg: json['errorMsg'],
      createdAt: json['createdAt'] != null
          ? DateTime.fromMillisecondsSinceEpoch(json['createdAt'])
          : null,
    );
  }

  // 生成提示词
  String toPrompt({
    required String stylePrefix,
    required bool forLocalSd,
  }) {
    // New logic: prompt = style + action (which contains the full scene description)
    // The 'action' field now holds the complete prompt generated by the analysis model.
    // e.g. "A beautiful garden, sunny day..."
    
    final cleanAction = action.trim();
    if (cleanAction.isEmpty) {
       return stylePrefix;
    }
    
    // For local SD, we might want to ensure it's English? 
    // But the analysis model is already instructed to output English for local SD.
    // So we just trust it.
    
    if (stylePrefix.isEmpty) {
      return cleanAction;
    }
    
    return '$stylePrefix, $cleanAction';
  }
}
